include:
  - component: $CI_SERVER_FQDN/dev-ops/templates/automatisation/ci-cd/pipeline-documentation-jupyterbook@~latest
    inputs:
      documentation_conf_file: "./docs/environment-docs.yml"
      documentation_sourcedir: "docs"
      documentation_builddir: "docs/_build/html/"

pages:
  stage: documentation
  extends:
    - .documentation:jupyterbook:gitlab-pages
  before_script:
    - apt-get update && apt-get install -y rsync
    - rsync -a notebooks/ docs/
  rules:
    - !reference [.documentation:publish:rules, rules]
    - when: always