include:
  - component: $CI_SERVER_FQDN/dev-ops/templates/automatisation/ci-cd/pipeline-documentation-jupyterbook@~latest

variables:
  DOCUMENTATION_CONDA_REQUIREMENTS: "./docs/environment-docs.yml"
  DOCUMENTATION_SOURCEDIR: "docs"
  DOCUMENTATION_BUILDDIR: "docs/_build/html/"

pages:
  stage: documentation
  extends:
    - .documentation:jupyterbook:gitlab-pages
  before_script:
    - apt-get update && apt-get install -y rsync
    - rsync -a notebooks/ docs/
  rules:
    - !reference [.documentation:publish:rules, rules]
    - when: never