variables:
  # DOCUMENTATION_CONDA_REQUIREMENTS: "ci/requirements/doc.yml"
  DOCUMENTATION_SOURCEDIR: ""
  DOCUMENTATION_BUILDDIR: "_build/html/"
  DOCUMENTATION_BASE_PYTHON_IMAGE: "gitlab-registry.ifremer.fr/ifremer-commons/docker/internal-images/mamba-poetry:24.7.1-2"

stages:
  - documentation

.documentation:python-conda:requirements:
  image: $DOCUMENTATION_BASE_PYTHON_IMAGE
  before_script:
    - mamba install -c conda-forge -n base mystmd
    # - mamba env update -f $DOCUMENTATION_CONDA_REQUIREMENTS -n base
    - myst --version

.documentation:myst:build:
  extends:
    - .documentation:python-conda:requirements
  script:
    - export HOST=127.0.0.1 # https://github.com/jupyter-book/mystmd/issues/2304
    - export BASE_URL="/vre/use-cases/1_bgc_argo"
    - myst build --html --keep-host

  artifacts:
    paths:
      - $DOCUMENTATION_BUILDDIR
    expire_in: 1 week

.documentation:myst:gitlab-pages:
  extends:
    - .documentation:myst:build
  after_script:
    - mv $DOCUMENTATION_BUILDDIR public
  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: documentation
  extends:
    - .documentation:myst:gitlab-pages