name: odatis-bgc-argo
channels:
  - conda-forge
dependencies:
  # Required dependencies
  - python>=3.9
  - notebook>=6.4.12
  - copernicusmarine>=2.2.3
  - numpy<2.0.0
  - xarray
  - pytcube
  - s3fs
  - pip
  - pip:
    - jupyterlab_myst

  # Docs dependencies
  - mystmd
  
  # Optional dependencies
  - ipykernel


